name: flutter_sapa_traffic_counter
description: Traffic Counter Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.1
  ### * For Dependency Injection & Route Management
  flutter_modular: ^5.0.3
  ### * For Device Scaling Type Like sp,r,sh & sw
  flutter_screenutil: ^5.5.3+2
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  ### * View Model State Management
  pmvvm: ^4.0.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
  assets:
    - asset/image/icon/
    - asset/lang/